name: Build Library
run-name: Building new version of the flyout multifunction display app.
on: [push]

jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.26"

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Verify that build path exists
        run: mkdir -p ./out

      - name: Run Build Command.
        run: bash ./build.sh

      - name: Get Meta
        id: meta
        run: |
          echo REPO_VERSION=$(cat ./versioninfo.json | grep -i '"ProductVersion": "' | sed 's/    "ProductVersion": "/v/' | sed 's/"//') >> $GITHUB_ENV
          echo ${{ env.REPO_VERSION }}

      - name: Release
        uses: akkuman/gitea-release-action@v1
        with:
          prerelease: false
          draft: false
          tag_name: latest
          name: ${{ env.REPO_VERSION }}
          files: |
            ./out/MFD.exe
            ./out/MFD (Debug).exe
            ./icon.png

      - name: Send ntfy ping
        uses: niniyas/ntfy-action@master
        with:
          url: "${{ secrets.NTFY_URL }}"
          topic: "${{ secrets.NTFY_TOPIC }}"
          details: Workflow has been successfully completed!
